### check server status
GET http://localhost:8000

#======== Admin API
###post new admin user
POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
    "firstName":"Pradeep",
    "lastName":"Dhital",
    "email":"pradeep@gmail.com",
    "phone":"523442323",
    "dob":"03/09/2022",
    "address":"",
    "password":"pradeep"
}

###login
POST http://localhost:8000/api/v1/admin-user/login
Content-Type: application/json

{ 
    "email":"pradeep@gmail.com",
    "password":"pradeep"
}
#####============= categories action

### post category
POST http://localhost:8000/api/v1/categories
{
"status":"s"
}
