### check server status
GET http://localhost:8000

#======== Admin API
###post new admin user
POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
    "firstName":"Pradeep",
    "lastName":"Dhital",
    "email":"pradeep@gmail.com",
    "phone":"523442323",
    "dob":"03/09/2022",
    "address":"",
    "password":"pradeep"
}

###login
POST http://localhost:8000/api/v1/admin-user/login
Content-Type: application/json

{ 
    "email":"pradeep@gmail.com",
    "password":"pradeep"
}
#============= categories action

### post category
POST http://localhost:8000/api/v1/categories
Content-Type: application/json

{
"status":"active",
"name":"ipads",
"parentId":""
}


### get categories

GET http://localhost:8000/api/v1/categories


### delete category

Delete http://localhost:8000/api/v1/categories/6451c060e3e102740b4f7e99
