### check server status
GET http://localhost:8000

#======== Admin API
###post new admin user
POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
    "firstName":"Pradeep",
    "lastName":"Dhital",
    "email":"pradeep254@gmail.com",
    "phone":"523442323",
    "dob":"03/09/2022",
    "address":"",
    "password":"dfsdffdsfs"
}